version: 0.0
os: windows
files:
  - source: .\
    destination: C:\apps\conan-bot
hooks:
  BeforeInstall:
    - location: scripts\node-stop.bat
      timeout: 900
    - location: scripts\cleanup.ps1
      timeout: 900
  AfterInstall:
    - location: scripts\install.ps1
      timeout: 900
    - location: scripts\node-start.bat
      timeout: 900